<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerRucJdMA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRucJdMA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRucJdMA.legacy');
=======
if (\class_exists(\ContainerP4oHawR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP4oHawR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP4oHawR.legacy');
>>>>>>> 43c5919da8de4ffe83fbf06bc105707d87d51655

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerRucJdMA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRucJdMA\App_KernelDevDebugContainer([
    'container.build_hash' => 'RucJdMA',
    'container.build_id' => 'dc9ce9c4',
    'container.build_time' => 1582551708,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRucJdMA');
=======
    \class_alias(\ContainerP4oHawR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP4oHawR\App_KernelDevDebugContainer([
    'container.build_hash' => 'P4oHawR',
    'container.build_id' => '56ad8cb2',
    'container.build_time' => 1582551716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP4oHawR');
>>>>>>> 43c5919da8de4ffe83fbf06bc105707d87d51655
