<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9b3KOh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9b3KOh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV9b3KOh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV9b3KOh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV9b3KOh\App_KernelDevDebugContainer([
    'container.build_hash' => 'V9b3KOh',
    'container.build_id' => '13fbc5f1',
    'container.build_time' => 1582496796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9b3KOh');
