<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9jM9NZe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9jM9NZe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9jM9NZe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9jM9NZe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9jM9NZe\App_KernelDevDebugContainer([
    'container.build_hash' => '9jM9NZe',
    'container.build_id' => '8b2f9023',
    'container.build_time' => 1582553225,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9jM9NZe');
